export enum SONG_ACTIONS {
    GET_SONG = "GET_SONG",
    ADD_SONG = "ADD_SONG",
    DELETE_SONG="DELETE_SONG",
    EDIT_SONG = "EDIT_SONG",
}

export enum PLAYLIST_ACTIONS{
    GET_PLAYLIST = "GET_PLAYLIST",
    ADD_PLAYLIST = "ADD_PLAYLIST",
    DELETE_PLAYLIST= "DELETE_PLAYLIST",
    EDIT_PLAYLIST= "EDIT_PLAYLIST",

}